default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails-catbnb_development

test:
  <<: *default
  database: rails-catbnb_test

production:
  adapter:  postgresql
  encoding: utf8
  poll:     10
  host:     <%= ENV['POSTGRESQL_ADDON_HOST'] %>
  port:     <%= ENV['POSTGRESQL_ADDON_PORT'] %>
  database: <%= ENV['POSTGRESQL_ADDON_DB'] %>
  username: <%= ENV['POSTGRESQL_ADDON_USER'] %>
  password: <%= ENV['POSTGRESQL_ADDON_PASSWORD'] %>
